[package]
name = "stupid-spooder-game"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.12.0", features = ["wayland", "mp3"] }
rand = "0.8.5"

[target.wasm32-unknown-unknown]
runner = "wasm-server-runner"

